---
- name:  Prepare NFS server
  hosts:  nfs
  tasks:
    - name:  Ensure export directory exists
      file:
        path:  /exports
        state:  directory

    - name:  Ensure NFS is installed
      yum:
        name:  nfs-utils
        state:  latest

    - name:  Ensure NFS is enabled and started
      service:
        name:  nfs
        enabled:  true
        state:  started

#    - name: Ensure export entry is in /etc/exports
#      blockinfile:
#        path: /etc/exports
#        block: |
#          /exports *(rw,root_squash)
#        marker: "# {mark} ANSIBLE MANAGED BLOCK for OpenShift"

#    - name:  Re-export all NFS exports
#      shell:  exportfs -r
