---
- name:  Prepare NFS server
  hosts:  nfs
  tasks:
    - name:  Ensure export directories exist
      file:
        path:  "{{ item }}"
        state:  directory
      with_items:
        - /srv/exports/registry
        - /srv/exports/metrics
        - /srv/exports/logging
        - /srv/exports/pv

    - name:  Ensure NFS is installed
      yum:
        name:  nfs-utils
        state:  latest

    - name:  Ensure NFS is enabled and started
      service:
        name:  nfs
        enabled:  true
        state:  started

    - name: Ensure export entries are in /etc/exports
      blockinfile:
        path: /etc/exports
        block: |
          /srv/exports/registry *(rw,root_squash)
          /srv/exports/metrics *(rw,root_squash)
          /srv/exports/logging *(rw,root_squash)
          /srv/exports/pv *(rw,root_squash)
        marker: "# {mark} ANSIBLE MANAGED BLOCK for OpenShift"

    - name:  Re-export all NFS exports
      shell:  exportfs -r
