---
- name:  Prepare all nodes for running OpenShift
#  hosts:  nodes lb
  hosts:  nodes
  tasks:
  - name:  Ensure primary OpenShift software is installed
    yum:
      name: "{{ item }}"
      state:  latest
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct

  - name:  Ensure all software is updated
    yum:
      name:  "*"
      state:  latest
    notify:
      - reboot_system
      - hangout

  - name:  Ensure software for rpm-based installation is installed
    yum:
      name:  atomic-openshift-utils
      state:  latest

  - name:  Ensure Docker is installed
    yum:
      name:  docker-1.12.6
      state:  latest

  - name:  Ensure Docker service is running and enabled
    service:
      name:  docker
      enabled:  true
      state:  started

  handlers:
    - name:  reboot_system
      command:  "systemctl reboot"
      async:  1
      poll:  0
      ignore_errors:  true

    - name:  hangout
      become:  False
      wait_for:
        host:  "{{ inventory_hostname }}"
        state:  started
#        port:  22
        delay:  60
        timeout:  120
      delegate_to:  localhost
